name: LOFFER
description: 一个可以fork的博客
url: ''
baseurl: ''
avatar: 'https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/logo.png'
favicon: >-
  https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags
paginate: 8
excerpt_separator: <!-- more -->
footer-links:
  weibo: null
  behance: null
  dribbble: null
  email: null
  facebook: null
  flickr: null
  github: FromEndWorld/loffer
  instagram: null
  linkedin: null
  pinterest: null
  rss: null
  stackoverflow: null
  tumblr: null
  twitter: null
  youtube: null
footer-text: Copyright (c) 2019 来自中世界
disqus: loffer
gitalk:
  clientID: null
  clientSecret: null
  repo: null
  owner: null
  proxy: null
google_analytics: null
utteranc:
  repo: null
permalink: '/:title/'
paginate_path: '/page:num/'
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: ':expanded'
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
